### ISSUE TITLE
How to prevent duplicate springboot metrics from OTel collector using awsemfexporter

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#1067]
Hello,
I am running otel collector as sidecar for an app deployed in fargate.  awsemfexporter is flooding the otel log with the messages indicating  "Duplicate metric found". one example of the message is below. 

Q1:  How to prevent logging the WARN messages to otel log file?
Q2:  What is the cause of this?

2022-03-16T03:58:10.818Z	WARN	awsemfexporter@v0.25.0/grouped_metric.go:66	Duplicate metric found	{
    "kind": "exporter",
    "name": "awsemf/application",
    "Name": "jvm.gc.pause",
    "Labels": {
        "action": "end of minor GC",
        "cause": "G1 Evacuation Pause"
    }
}

**Comment by bryan-aguilar** [comment]
Can you please provide a copy of your collector config?

**Comment by georges-git** [comment]
It is the standard config from aws.
So otel side car config value is:  /etc/ecs/container-insights/otel-task-metrics-config.yaml

**Comment by p120ph37** [comment]
Here is a simple Spring Boot application which produces offending metrics:
https://github.com/p120ph37/statsd-example

As George mentioned above, this requires an otel collector configuration with statsd enabled, such as the `container-insights/otel-task-metrics-config.yaml`, or the base `config.yaml` with a `statsd` endpoint added like this:
```
receivers:
  statsd:
    endpoint: 0.0.0.0:8125
    aggregation_interval: 60s
... 
service:
  pipelines:
    traces:
      receivers: [otlp,awsxray]
      processors: [batch/traces]
      exporters: [awsxray]
    metrics:
      receivers: [statsd,otlp]
      processors: [batch/metrics]
      exporters: [awsemf]
```

In my example app, the specific offending metric is `jvm.gc.pause`.  I forced this artificially by calling `System.gc()` for reproducibility's sake, but in a real-world scenario, GC events are often triggered by actual application load and activity, so the issue may not be immediately-obvious until the app comes under load.

Looking into how and where this metric is generated, we see that is is produced within `micrometer-core`, in the `JvmGcMetrics` class [here](https://github.com/micrometer-metrics/micrometer/blob/3eb507247e1fc907ed85f0aa4daaead3e68c9375/micrometer-binders/src/main/java/io/micrometer/binder/jvm/JvmGcMetrics.java#L180).   That code produces a `Timer` record each time GC runs.  For stateless `MeterRegistry` implementations, such as `micrometer-meterregistry-statsd`, this causes
each record to be emitted immediately by default, rather than accumulated into a histogram as would be the case for something stateful like `micrometer-meterregistry-prometheus`.  This means that each time a GC event fires, a separate UDP packet is emitted to the `statsd` address.

In the case where the `statsd` collector is an `aws-otel-collector` instance, these `Timer` datapoints are handled separately by default, and passed through the pipeline to the emitter - which is `awsemf` in this particular scenario.   Although the default pipeline does do some batching, the `batchprocessor` module does not aggregate `Timer` metrics into histograms, so it ends up passing them as an array of individual items to `awsemfexporter`, which sends them as separate EMF documents to the CloudWatch metrics logstream.  This can be very inefficient in some cases, particularily when dealing with very-high-volume `Timer` metrics.  The example GC metric I've discussed so far is seldom very high-frequency, but other metrics are, such as HikariCP's `hikaricp.connections.*` metrics (defined [here](https://github.com/brettwooldridge/HikariCP/blob/da838d36fa85fabcdd671a1fa4d9e22392e9e9a3/src/main/java/com/zaxxer/hikari/metrics/micrometer/MicrometerMetricsTracker.java#L80-L93)), or especially Spring MVC's `server.http.request`, which emits _once per request_, and can easily amount to hundreds or thousands of EMF documents per batch!  This runs the risk of overloading the CloudWatch logstream throttle, and of incurring unexpectedly-large costs for datapoint ingestion.

The most direct workaround right now appears to be to add a `timer_histogram_mapping` directive to the `statsd` collector:
```
receivers:
  statsd:
    endpoint: 0.0.0.0:8125
    aggregation_interval: 60s
    timer_histogram_mapping:
      - statsd_type: histogram
        observer_type: summary
      - statsd_type: timing
        observer_type : summary
```
That causes the `statsdcollector` to aggregate `Timer` datapoints into a summary, and as long as the `aggregation_interval` on that collector is equal to or less than any `batchprocessor` `timeout` value for that pipeline, you do not get the duplicate EMF documents or warnings due to frequent `statsd` `Timer` metrics.

Another possible workaround is to avoid using the `micrometer-meterregistry-statsd` and `statsdcollector` modules altogether for Spring Boot / Micrometer metrics, and instead use the `micrometer-meterregistry-prometheus` and the `prometheuscollector` modules, which tend to handle metric-aggregation more-efficiently.  (A `micrometer-meterregistry-otlp` module might be good to have, but such a thing doesn't seem to exist quite yet - though the beginnings of it seem to be starting in the [java-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/micrometer/micrometer-1.5) project)

Besides the scenario where duplicate datapoints arrive due to frequent `statsd` `Timer` events, there is also an issue where flattening metric dimensions within the `awsemfexporter` by using a `metrics_declarations` directive can result in the flattened metrics being considered duplicates within the `awsemfexporter` module itself and generating warnings.  In that scenario, adjusting the `statsdcollector` configuration isn't helpful because the duplication comes about later in the pipeline.  The workaround for _that_ issue is that it is usually more-reliable to flatten dimensions by using the `metricstrandformprocessor` module's `aggregate_labels` action than to rely on `awsemfexporter` to do it, however that cannot be applied to "summary" datatypes due to open-telemetry/opentelemetry-collector-contrib#6504

**Comment by p120ph37** [comment]
Here is an example of the EMF output before applying `timer_histogram_mapping` in the `statsdcollector`:
```
2022-03-24T19:12:42.324-05:00 {
    "_aws": {
        "CloudWatchMetrics": [
            {
                "Namespace": "default",
                "Dimensions": [
                    [
                        "action",
                        "cause"
                    ],
                    [],
                    [
                        "action"
                    ],
                    [
                        "cause"
                    ]
                ],
                "Metrics": [
                    {
                        "Name": "jvm.gc.pause"
                    }
                ]
            }
        ],
        "Timestamp": 1648167162324
    },
    "action": "end of major GC",
    "cause": "System.gc()",
    "jvm.gc.pause": 79
}
2022-03-24T19:12:52.309-05:00 {
    "_aws": {
        "CloudWatchMetrics": [
            {
                "Namespace": "default",
                "Dimensions": [
                    [
                        "action",
                        "cause"
                    ],
                    [],
                    [
                        "action"
                    ],
                    [
                        "cause"
                    ]
                ],
                "Metrics": [
                    {
                        "Name": "jvm.gc.pause"
                    }
                ]
            }
        ],
        "Timestamp": 1648167172309
    },
    "action": "end of major GC",
    "cause": "System.gc()",
    "jvm.gc.pause": 63
}
2022-03-24T19:13:02.091-05:00 {
    "_aws": {
        "CloudWatchMetrics": [
            {
                "Namespace": "default",
                "Dimensions": [
                    [
                        "action",
                        "cause"
                    ],
                    [],
                    [
                        "action"
                    ],
                    [
                        "cause"
                    ]
                ],
                "Metrics": [
                    {
                        "Name": "jvm.gc.pause"
                    }
                ]
            }
        ],
        "Timestamp": 1648167182091
    },
    "action": "end of major GC",
    "cause": "System.gc()",
    "jvm.gc.pause": 46
}
```

Versus after:
```
2022-03-25T16:32:03.808-05:00 {
    "_aws": {
        "CloudWatchMetrics": [
            {
                "Namespace": "default",
                "Dimensions": [
                    [
                        "action",
                        "cause"
                    ],
                    [],
                    [
                        "action"
                    ],
                    [
                        "cause"
                    ]
                ],
                "Metrics": [
                    {
                        "Name": "jvm.gc.pause"
                    }
                ]
            }
        ],
        "Timestamp": 1648243923808
    },
    "action": "end of major GC",
    "cause": "System.gc()",
    "jvm.gc.pause": {
        "Max": 62,
        "Min": 56,
        "Count": 3,
        "Sum": 176
    }
}
```
