### ISSUE TITLE
XRay exporter is failing the exports to the collector 

### ISSUE THREAD

**Issue by rakyll** [aws-observability/aws-otel-collector#129]
When exporting spans to the collector via `aws-opentelemetry-agent-0.9.0.jar`, the user sees the following error. Switching to Jaeger export on the collector resolves the problem. 

```
WARN io.opentelemetry.exporters.otlp.OtlpGrpcSpanExporter - Failed to export spans
io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 952949744ns. [buffered_nanos=957880184, waiting_for_connection]
```

**Comment by mxiamxia** [comment]
This is due to the breaking changes on the data compatibility in OpenTelemetry SDK updates from 0.9.0 to 0.10.0. We have to ask all the customers use the latest `OTel SDK(`> v0.10.0) and `aws-opentelemetry-agent`(> v0.10.0) that can work with the latest AWS OTel Collector.

To download the latest `aws-opentelemetry-agent`,
```
<dependency>
  <groupId>software.amazon.awsobservability</groupId>
  <artifactId>aws-opentelemetry-agent</artifactId>
  <version>0.10.1-aws.1</version>
</dependency>
```
or

`wget https://github.com/aws-observability/aws-otel-java-instrumentation/releases/download/v0.10.1-aws.1/aws-opentelemetry-agent.jar`

**Comment by rakyll** [comment]
Ah client/collector compatibility is not handled by OpenTelemetry so far and no compatibility-related errors are produced. Maybe we can raise this as an issue.
