### ISSUE TITLE
Image v0.21.1 crashloop on EKS fargate nodes with kubernetes version 1.23

### ISSUE THREAD

**Issue by cmanfre4** [aws-observability/aws-otel-collector#1487]
**Describe the bug**
I recently upgraded my EKS cluster from kubernetes version 1.22 to 1.23. After the upgrade when I recycled my adot-collector pod, it's now crashlooping with the following error:

Error: failed to create containerd task: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: failed to write "200000": write /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod821d86a3-2627-450a-9a50-16dbfd2aff26/adot-collector/cpu.cfs_quota_us: invalid argument: unknown

Some googling suggests this to be an issue with cgroups version2 and the kernel. Per the following:

https://github.com/opencontainers/runc/issues/2959#issuecomment-847521031
https://github.com/opencontainers/runc/blob/main/docs/cgroup-v2.md

When I check the kernel version of a pod running in the new EKS fargate nodes with the new Kubernetes version, I'm getting the following, which apparently does not support cgroups v2:

4.14.287-215.504.amzn2.x86_64

**Steps to reproduce**
Use the following image in EKS with fargate, running Kubernetes version 1.23:
https://hub.docker.com/layers/amazon/aws-otel-collector/v0.21.1/images/sha256-78bf7f5444cb9c55774ec02171e932529e8632fcc8ec628c0e651e1a6a9abde0

**What did you expect to see?**
I expected the pod to recycle without issue.

**What did you see instead?**
The pod is now stuck in a crashloop.

**Environment**
EKS with fargate, running Kubernetes version 1.23

**Additional context**
I'm not sure if this is the correct place to ask for a fix. I didn't get a chance to confirm the Kernel version of my older 1.22 fargate nodes. Maybe AWS should revert to the previous Kernel where this was working?

**Comment by omallo** [comment]
@cmanfre4 , I was having the same error on EKS with Kubernetes 1.23 and Fargate. In my case, it turned out that the problem is triggered by the pod resource configuration where the requests and limits were not set to the same value as mandated in the [AWS documentation](https://docs.aws.amazon.com/eks/latest/userguide/fargate-pod-configuration.html).

In my toy example, I had the following pod resource configuration:
```yaml
resources: 
  requests: 
    cpu: "200m"
    memory: "128Mi"
  limits: 
    cpu: "400m"
    memory: "256Mi"
```
With that configuration, Fargate allocated a node with 0.25vCPU and 0.5GB of memory. Apparently, the CPU sizing is done based on the requested resources but Fargate then tries to set the CPU to the value in the resource limits which fails since the CPU limits are higher than the overall CPU of the node.

I'm not sure whether you might be experiencing the same problem but you might want to try setting the resource requests/limits to the same value if that's currently not the case. That solved the problem for me.

**Comment by gmconte** [comment]
This workaround doesn't work for me.

My original error was 
`Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: failed to write "200000": write /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod58808a74-73a8-463b-ad3c-71fb6e22d705/adot-collector/cpu.cfs_quota_us: invalid argument: unknown`

Now, after the change mentioned by @cmanfre4, the error is only slightly changed:
`Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: failed to write "40000": write /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod60636f9d-0b4b-4f2f-a763-9e176770fe4b/adot-collector/cpu.cfs_quota_us: invalid argument: unknown
`

Looking at the error, I wonder if this is linked to [Amazon EKS is ending support for Dockershim](https://docs.aws.amazon.com/eks/latest/userguide/dockershim-deprecation.html)?

Any ideas on how to avoid this issue?

**Comment by gmconte** [comment]
Yep, I can confirm it too now. 
I misread the suggestion made by @cmanfre4.

I now asked AWS to make this requirement (limits = request) more apparent in the documentation with an explanation of the consequences, considering that it has been enforced only from EKS 1.23.

So, the workaround is ok, but that section in the file https://github.com/aws-observability/aws-otel-collector/blob/6b7244de7f3bfa9cd733d3183fdcbedfacd7815f/deployment-template/eks/otel-fargate-container-insights.yaml#L534 should be changed.

In the meantime, what would be a sensible value to set? the minimum? Or it depends on how many pods are in the cluster?
Can you please advise?

**Comment by n1nj4-r4cc00n** [comment]
It's hard to say since it will depend entirely on the application you are deploying on your pods. With `Fargate`, you can think of each pod as a "node", so essentially is how much compute capacity needs your application to run on a pod. If your application needs 1 CPU and 4GB of memory to run then those are your limits. As of now, AWS maps one pod per Fargate node and Fargate needs at least 45seconds to create a new instance. So if your application will be scaling dynamically the number of pods I suggest you to use Managed node groups instead of Fargate

**Comment by gmconte** [comment]
Well, I was asking more specifically with regards to this Otel Collector...

**Comment by csmithfwi** [comment]
Thank you this helped solve this problem for me with the ADOT Collector and the CloudHealth Collector.

> @cmanfre4 , I was having the same error on EKS with Kubernetes 1.23 and Fargate. In my case, it turned out that the problem is triggered by the pod resource configuration where the requests and limits were not set to the same value as mandated in the [AWS documentation](https://docs.aws.amazon.com/eks/latest/userguide/fargate-pod-configuration.html).
> 
> In my toy example, I had the following pod resource configuration:
> 
> ```yaml
> resources: 
>   requests: 
>     cpu: "200m"
>     memory: "128Mi"
>   limits: 
>     cpu: "400m"
>     memory: "256Mi"
> ```
> 
> With that configuration, Fargate allocated a node with 0.25vCPU and 0.5GB of memory. Apparently, the CPU sizing is done based on the requested resources but Fargate then tries to set the CPU to the value in the resource limits which fails since the CPU limits are higher than the overall CPU of the node.
> 
> I'm not sure whether you might be experiencing the same problem but you might want to try setting the resource requests/limits to the same value if that's currently not the case. That solved the problem for me.

Thank you this helped solve this problem for me with the ADOT Collector and the CloudHealth Collector.

**Comment by rapphil** [comment]
the workaround provided by @omallo is correct.

In the case of the eks add-on you have to first enable it and then edit the deployment:
`kubectl edit deployment opentelemetry-operator-controller-manager -n opentelemetry-operator-system`

Then make sure that requested and limit values are the same.
