### ISSUE TITLE
Flamegraphs in OTEL traces (AWS CloudWatch-Traces) and AWS-XRay

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#1518]
Hello, What is the timeline for flamegraphs be available in OTEL traces (CloudWatch-Traces) and XRay?

**Comment by mhausenblas** [comment]
Not sure what you mean with flame graphs support in OpenTelemetry  (since these are a visualization technique used in frontends). Having said that, in order to create flame graphs (or icicle graphs) one needs profiles as input data. The support for [profiles](https://github.com/open-telemetry/oteps/blob/main/text/profiles/0212-profiling-vision.md) upstream is a very new activity that, while we're very supportive of and excited about, will take a while to land.
