### ISSUE TITLE
Performance model should include throughput

### ISSUE THREAD

**Issue by albertvaka** [aws-observability/aws-otel-collector#209]
**Description of the problem**
The [performance model](https://github.com/aws-observability/aws-otel-collector/blob/master/docs/performance_model.md) currently measures CPU and memory, but not requests/second. 

**Motivation**
From my experience at Datadog, that is an important measure to take into account when comparing different solutions (eg: single threaded vs multi-threaded) and can help identify problems (eg: mutexes causing contention).

**Additional context**
The implementation can be as simple as measuring the time from beginning to end of the test and dividing between the number of requests.

**Comment by wyTrivail** [comment]
@albertvaka thx for the suggestion!

Right now we have the `TPS` parameter in the performance model if you check the header in each table. like 100TPS.

And we are also working on to [measure a TPS data](https://github.com/aws-observability/aws-otel-test-framework/blob/terraform/mocked_servers/https/index.js#L14) from the mocked_server, so that we can know how many requests are sent out to the server. 

If the two measurements can not match your suggestion, maybe you can explain a bit more?

**Comment by albertvaka** [comment]
My understanding is that those TPS in the header represent the rate at which the collector is fed, not the rate at which the metrics come out on the other end, from the exporter. 

In theory, you could send 100 request per second for 10 seconds (1000 requests total) to a collector that can only process 1 request per second, causing it to queue them and taking it 1000 seconds to empty the queue. Hence why the total run time becomes important.

**Comment by wyTrivail** [comment]
@albertvaka  thx for elaborating! and yes it make much sense to measure how quick can the collector handle data. and this is what we are working on recently to measure the tps received in server side.  I'm closing this issue and will let you know once we finish that. 

Thanks again! :)
