### ISSUE TITLE
SQL Instrumentation Error - Invalid Subsegment

### ISSUE THREAD

**Issue by aivand2l** [aws-observability/aws-otel-collector#390]
Hello, my .NET Core code is instrumented with OpenTelemetry version 1.0.1 and that traces are exported to XRay using the AWS Otel collector version 0.7.0 . The tracing works as expected for the endpoint traces however when the collector tries to send a span for a SQL command, the collector shows the error shown below and those spans don't show up in XRay. 
I have confirmed that the same spans show up in Jaeger when using the Jaeger exporter. 

Does anyone else have the same issue? Any recommendations on how to get this working?

**Comment by mxiamxia** [comment]
Hi @aivand2l, could you attach the collector logs with the errors you mentioned?

**Comment by aivand2l** [comment]
Hi @mxiamxia, thanks for you reply. My apologies, I just noticed that I missed attaching the log to my original inquiry so I will add it right now. 
The error I mentioned will be the very last message in the log.

[aws_otel_collector_log.txt](https://github.com/aws-observability/aws-otel-collector/files/6142580/aws_otel_collector_log.txt)

**Comment by anuraaga** [comment]
@aivand2l It looks like the hostname that's being read has a comma instead of colon

`dams-rds2.c8g8niwwk1si.us-east-1.rds.amazonaws.com,1433`

Commas aren't allowed in names, and we wouldn't expect them in hostnames
https://docs.aws.amazon.com/xray/latest/devguide/xray-api-segmentdocuments.html

Do you know why that's a comma? Could it be a problem with .NET instrumentation?
