### ISSUE TITLE
Using aws credentials file which rotates access key and access secret

### ISSUE THREAD

**Issue by CathalAherne** [aws-observability/aws-otel-collector#408]
Hi

We are using the aws-otel-collector on prem. We therefore use an aws credentials file. We have a sidecar which rotates these credentials once they expire. It seems the collector only reads the credentials file once and doesn't re-read the file if the credentials expire. This error is logged by the collector:
`"error": "Permanent error: ExpiredTokenException`
The recommendation is not to give permanent credentials to services so this is a feature we would expect to be supported.

**Comment by navsinha5** [comment]
Hi @CathalAherne,

Going a bit out of the topic here. Since you are also using the collector on prem, could you help me out with #407 this issue please? I am using EC2 for a POC but the plan is to deploy on prem afterwards.

**Comment by mxiamxia** [comment]
Hi @CathalAherne, Thanks for catching this issue. In the current AWS EMF/Metrics and X-Ray/Trace exporters, we create a singleton AWS connection session when the exporters are initialized. It won't be refreshed unless the collector is restarted if you're using the shared credential files. (IAM role auth should work automatically because AWS SDK will refresh sts token behind the scene).

We'll add the retry to refresh the session if the token is expired. We can get the fix released in April. Thanks for reporting the issue. 

The code where the singleton session was created,
https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/awsemfexporter/emf_exporter.go#L62

**Comment by mxiamxia** [comment]
> Hi @CathalAherne,
> 
> Going a bit out of the topic here. Since you are also using the collector on prem, could you help me out with #407 this issue please? I am using EC2 for a POC but the plan is to deploy on prem afterwards.

Hi @navsinha5 , I also replied your thread. Could you try to replace `amppromethuesexporter` to `emfexporter` to see if it works for you first. Thank you for reporting the findings with us. :)

**Comment by CathalAherne** [comment]
Great, thanks @mxiamxia

**Comment by CathalAherne** [comment]
Hello,

Is there any update on this issue? It looks like the changes MR has been closed without being merged:
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3175

**Comment by GarrettBeatty** [comment]
is there a reason this issue was closed? its still applicable no?
