### ISSUE TITLE
get the latest "aws-opentelemetry-agent.jar" in DockerFile

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#558]
Hello @mxiamxia and AWS team:

In the Dockerfile of my java app running on EC2: 

I am using ADD command trying to pull the latest "aws-opentelemetry-agent.jar".   What is the path to the  latest version of this jar? 

**Would this work - ADD https://github.com/aws-observability/aws-otel-java-instrumentation/releases/latest/download/aws-opentelemetry-agent.jar**

**Comment by sethAmazon** [comment]
https://github.com/aws-observability/aws-otel-java-instrumentation/releases/download/v1.2.0/aws-opentelemetry-agent.jar

will download the latest release of v1.2.0

**Comment by sethAmazon** [comment]
https://aws-otel.github.io/docs/getting-started/java-sdk/trace-auto-instr

"Running the agent in Docker
If your app is packaged in Docker, the easiest way to run with the agent is to use the JAVA_TOOL_OPTIONS environment variable, which automatically sets flags for java. Adding this snippet to your Dockerfile will typically be enough to enable tracing, although if you already set JAVA_TOOL_OPTIONS, don't forget to make sure to add to your existing setting rather than replacing it.

Copy
ADD https://github.com/aws-observability/aws-otel-java-instrumentation/releases/latest/download/aws-opentelemetry-agent.jar /opt/aws-opentelemetry-agent.jar
ENV JAVA_TOOL_OPTIONS=-javaagent:/opt/aws-opentelemetry-agent.jar"
