### ISSUE TITLE
--config=/etc/ecs/container-insights/otel-task-metrics-config.yaml"

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#603]
Hello:

I am using “--config=/etc/ecs/container-insights/otel-task-metrics-config.yaml" in the Environment section of my container definition for my otel collector running as a sidecar in the Fargate task.

1)      Does this point to your git location : aws-otel-collector/config/ecs/container-insights/otel-task-metrics-config.yaml

2)      How to make this to point my “otel-task-metrics-config.yaml” in my git?

**Comment by willarmiros** [comment]
Hi George,

By "environment section" do you mean you're setting some environment variable? 

Q1: Yes, that's where the [task metrics](https://github.com/aws-observability/aws-otel-collector/blob/main/config/ecs/container-insights/otel-task-metrics-config.yaml) config file lives on github. But our [Dockerfile](https://github.com/aws-observability/aws-otel-collector/blob/1252c4ba9eed7197e32a22af51d821c27f6097fa/cmd/awscollector/Dockerfile#L52) copies it to the specified location in `/etc`.

Q2: The `--config` is a command line argument to the collector executable. If you're following the [documented instructions](https://github.com/aws-observability/aws-otel-collector/blob/main/docs/developers/ecs-demo.md#install-awsotelcollector-on-ecs-fargate) and using our CFN template, then you need to be sure you're setting the `command` parameter when creating the CFN stack. Otherwise, you just have to find a way for passing the `--config=/path/to/config/on/my/container` option to your collector if you're using a custom setup.

**Comment by georges-git** [comment]
Hello William,
1) Environment is the standard section in the container definition as part of your fargate task definition

2) Since the above file "/etc/ecs/container-insights/otel-task-metrics-config.yaml" is for ECS and filters task metrics like "ecs.task.memory.reserved". **Could you provide a config file for EC2 which filters host metrics like cpu, mem, disk i/o time, disk iops, process open filedescriptor for a specific process, cpu load average, network stats etc?**

**Comment by mxiamxia** [comment]
Has a meeting with George today on these issues. Closed the issue unless there are more questions.
