### ISSUE TITLE
Include AWS Resource Detectors by Default

### ISSUE THREAD

**Issue by willarmiros** [aws-observability/aws-otel-collector#62]
We should modify our vended `config.yaml` to include the all AWS-specific [resource detectors](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/processor/resourcedetectionprocessor/README.md#resource-detection-processor) on the collector. #32 is a first attempt at this, but it is still TBD whether we should include the `env` resource detector. Eventually, we should have detectors for:

* EC2
* ECS
* EKS (Although the k8s detector could potentially suffice)
* Elastic Beanstalk
* Lambda

**Comment by mxiamxia** [comment]
Hi William, looked the #32 , I think we need to fix the following things before we can merge it into the collector,
1. Update the integration test package, at lease  we need to update our Traces data validator to verify new attributes created by processor are expected.
2. The new processor is not built in the collector yet, Your CR should include the same change, otherwise, the collector will be failed to start with the new default config file.
Thanks.

**Comment by willarmiros** [comment]
I closed #32, I think a larger change is going to be necessary based on your comments. We also have not yet added many of the translation capabilities to convert AWS resource attributes to fields in X-Ray segments. I think once https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1360 is merged along with a corresponding data model translation PR, I'll circle back to this and the integ test changes.

**Comment by pingleig** [comment]
It's already included https://github.com/aws-observability/aws-otel-collector/blob/0134db77f6b4f1c8263e7423179a715cb233b485/pkg/defaultcomponents/defaults.go#L29
