### ISSUE TITLE
How to configure histograms?

### ISSUE THREAD

**Issue by kvcache** [aws-observability/aws-otel-collector#651]
I'm looking for a way to tease histograms (SEH in aws parlance) out of my application. I'm emitting `Histogram` OTLP type data (via java api `DoubleHistogramData`).

I see in CloudWatch that the EMF exporter has mangled my histogram data to just min, max, sum and count (which is not a histogram).

I configured stdout json on the emf exporter just to sanity check, and saw the same mangling, so I also enabled Otel debug logging and see that indeed the OTLP receiver passes `Histogram` data to the Logging processor exactly as I sent, but then the log lines from the EMF exporter show those same measurements stripped of their Histogram data.

How do I use Histograms with CloudWatch?

**Comment by guseggert** [comment]
I have the same question. How can I get e.g. latency histograms from CW with OpenTelemetry? 

Additionally, it looks like the counter is wrong? If I record a metric event and then another one a few minutes later, this shows up as count=3 in CloudWatch, because it seems like the EMF exporter is using a cumulative counter (emits "1" then "2") which CW then sums up.

**Comment by alolita** [comment]
Hi @kvcache CW histograms are currently incompatible with histograms supported by OTLP. There is ongoing work on the project to support exponential histograms. That is a precursor for supporting CW histograms in the long run.

**Comment by kvcache** [comment]
Thanks for the reply @alolita! Good luck with the histogram project!

**Comment by devharis** [comment]
Hey - just saw this and I'm also looking for a solution to this too.
Is there any progress and hopefully a guesstimate on when we can expect it to be supported? 😊

**Comment by s33kers** [comment]
Any news?

**Comment by RafaelWO** [comment]
Hello, we use the ADOT collector to collect traces and metrics from Python FastAPI services. Metrics like [`http.server.active_requests`](https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserveractive_requests) (UpDownCounter) are shown correctly in CloudWatch, but [`http.server.request.duration`](https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestduration) (Histogram), which is a crucial metric, is not not - I guess due to the conversion to min, max, sum and count.

It would be great if the EMF exporter and CloudWatch supported histograms.

**Comment by fmhwong** [comment]
We are trying to visualize `http.server.request.duration` on CW and encountered the same problem.
