### ISSUE TITLE
Is AWS-OTEL-Collector generally available and link to download docker tar ball

### ISSUE THREAD

**Issue by thisisronak** [aws-observability/aws-otel-collector#737]
**Describe the question**
Q1) We are planning to use AWS-OTEL-Collector library for our open tracing requirements inside my organization. I was looking at the run OTEL with Docker page, https://github.com/aws-observability/aws-otel-collector/blob/main/docs/developers/docker-demo.md, which says this is currently in beta. Wanted to understand from the team about the status of the library and if it is generally available for use!

Q2) Please provide the link to download the docker tar ball.

**Comment by thisisronak** [comment]
Bumping this up, in case it flew under the radar

**Comment by alolita** [comment]
@thisisronak The AWS Distro for OpenTelemetry (ADOT) Collector has GA'ed tracing support. Note metrics or logs support is not GA/prod ready since the upstream project OpenTelemetry does not support stable metrics or logs yet.

For more details see https://aws.amazon.com/blogs/opensource/aws-distro-for-opentelemetry-is-now-ga-for-tracing/

Please note AWS support for ADOT Collector for tracing is available only if you have AWS support. If you don't please feel free to ask questions here on GitHub and we will try to help bandwidth permitting.

**Comment by thisisronak** [comment]
@alolita Thanks for reverting back! I was also wondering if you can share the download link to the tar file of the docker image

**Comment by DarwinSin** [comment]
Hi team - can you share the otel collector image (preferably as a tar ball) that we can use?

**Comment by alolita** [comment]
Hi @DarwinSin @thisisronak - The ADOT Collector image can be downloaded at public.ecr.aws/aws-observability/aws-otel-collector:latest

You can always find the latest image from this link - https://aws-otel.github.io/download

**Comment by sethAmazon** [comment]
@alolita may I close this issue?

**Comment by alolita** [comment]
Closed.
