### ISSUE TITLE
Using AWS OTEL Collector

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#741]
Hello, 

1) If i want only 1% sample of open telemetry traces sent to Cloudwatch, would the following configuration assist in achieving that?

OTEL_TRACES_SAMPLER=parentbased_always_on
OR
OTEL_TRACES_SAMPLER=parentbased_traceidratio
OTEL_TRACES_SAMPLER_ARG=.01

From the above two which sampler to use?

2) Do i need to pass OTEL_TRACES_SAMPLER or just using OTEL_TRACES_SAMPLER_ARG is enough to control the sampling rate ?

3) Does the above variables could be passed as shell environment variables or does it need to be passed on the JAVA command line as arguments?

**Comment by NathanielRN** [comment]
Hi @georges-git,

> 1. If i want only 1% sample of open telemetry traces sent to Cloudwatch, would the following configuration assist in achieving that?

It's my understanding that `always_on` means `100%` sampling so that's probably not what we want. The `parent_based` part means it follows the decision of the parent first for sampling.

Instead I think you are correct that `parentbased_traceidratio` with `0.01` should work. You could be more restrictive and use `traceidratio` alone without the parent if you want.

> 2. Do i need to pass OTEL_TRACES_SAMPLER or just using OTEL_TRACES_SAMPLER_ARG is enough to control the sampling rate ?

I think you need to provide _both_. [The default sampler for OTel Java is the `always_on` sampler](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkTracerProviderBuilder.java#L19) which will not respect your `1%`.

> 3. Does the above variables could be passed as shell environment variables or does it need to be passed on the JAVA command line as arguments?

Environment variables should work, otherwise it [looks like you can use Java program arguments](https://github.com/open-telemetry/opentelemetry-java/blob/main/CHANGELOG.md#auto-configuration-alpha-3) something like this (untested configuration)

`-Dotel.traces.sampler=parent_based_traceidratio -Dotel.traces.sampler.arg=ratio=0.01`
