### ISSUE TITLE
Sort out ADOT sample apps

### ISSUE THREAD

**Issue by anuraaga** [aws-observability/aws-otel-collector#746]
Currently, we have a sample app in each ADOT ADK repo for integration tests, and also sample apps for prometheus and the collector. We should list these out in a central location, clarify their use cases (e.g., OTEL SDK vs Prometheus), dedupe (I think the aws-otel-test spark app is the same as the one in the aws-otel-java repo).

**Comment by sethAmazon** [comment]
What we have so far 


Repo | App Name | Location | App function | Language | Repo type | Last updated | Person in charge | Most recent commit | Note
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
aws-otel-test-framework | Spark | https://github.com/aws-observability/aws-otel-test-framework/tree/terraform/sample-apps/spark | otlp xray and traces to collector | Java | Integration Tests | Update in progress |   |   |  
Jmx | https://github.com/aws-observability/aws-otel-test-framework/tree/terraform/sample-apps/jmx | Generates prometheus metrics | Java | Integration Tests | 4/19/2021 | pingleig, bjrara |   |  
Jaeger-Zipkin | https://github.com/aws-observability/aws-otel-test-framework/tree/terraform/sample-apps/jaeger-zipkin-sample-app | Emit trace data using zipkin and jaeger | Java | Integration Tests | 8/27/2021 | amanbrar1999 ,mingxia |   |  
Prometheus | https://github.com/aws-observability/aws-otel-test-framework/tree/terraform/sample-apps/prometheus | Emit prometheus metrics | Go | Integration Tests | 8/27/2021 | amanbrar1999 ,mingxia |   |  
Statsd | https://github.com/aws-observability/aws-otel-test-framework/tree/terraform/sample-apps/statsd | Send metrics with statsd format | Python | Integration Tests | 5/17/2021 | gavindoudou |   |  
aws-otel-community | Prometheus sample app community | https://github.com/aws-observability/aws-otel-community/tree/master/sample-apps/prometheus | - Testing prometheus's metrics (counter,gauter,histogram,summary) | Go |   | 12/9/2020 | amanbrar |   |  
aws-otel-js | Javascript sample app | https://github.com/aws-observability/aws-otel-js/tree/main/sample-apps | - Core function: Continuous integration of ADOT components for X-Ray with Manual instruemntation of OpenTelemetry JavaScript SDK | Javascript | X-ray sample app | 9/22/2021 | NathanielRN |   |  
aws-otel-python | Python auto instrumentation sample app | https://github.com/aws-observability/aws-otel-python/tree/main/integration-test-apps/auto-instrumentation/flask | - Core function: Conitinuous integration of ADOT components for X-Ray with Auto instrumentation of OpenTelemetry Python - Setting up the python sample-app to auto instrument instead of manual instrument | Python | X-ray sample app | 10/14/2021 | NathanielRN |   | Another thing is that in the github action workflow: https://github.com/aws-observability/aws-otel-python/blob/3e4d43fe6d16ebd3f790fd60e29c1bb03cea219e/.github/workflows/integration-testing.yml#L69-L78 is showing that it is validating the sample app
Python manual instrumentation sample app | https://github.com/aws-observability/aws-otel-python/tree/main/integration-test-apps/manual-instrumentation/flask | - Core function: Conitinuous integration of ADOT components for X-Ray with Manual instrumentation of OpenTelemetry Python | Python | X-ray sample app | 10/18/2021 | NathanielRN |  
Python no instrumentation sample app | https://github.com/aws-observability/aws-otel-python/tree/main/integration-test-apps/none-instrumentation/flask | - Core function: use non-instrumentation for performance reference | Python | X-ray sample app | 9/20/2021 | NathanielRN |   |  
aws-otel-go | Go sample app | https://github.com/aws-observability/aws-otel-go/tree/main/sampleapp | - Core function: Complement the upstream OpenTelemetry Go with components for X-Ray | Go | X-ray sample app | 10/27/2021 | anuraaga,bhautikpip,anthony |   |  
aws-otel-dotnet | .NET sample app | https://github.com/aws-observability/aws-otel-dotnet/tree/main/integration-test-app | - Core function: Complement the upstream OpenTelemetry .NET with components for X-Ray | .NET | X-ray sample app | 9/23/2021 | lupengamzn |   |  
aws-otel-java-instrumentation | Spark-awssdkv1 | https://github.com/aws-observability/aws-otel-java-instrumentation/tree/main/sample-apps/spark-awssdkv1 | Emit metrics to Xray | Java | X-ray sample app | 9/22/2021 | NathanielRN, anuraaga |   |  
Spark | https://github.com/aws-observability/aws-otel-java-instrumentation/tree/main/sample-apps/spark | Emit metrics to Xray | Java | X-ray sample app | 9/22/2021 | NathanielRN, anuraaga |   |  
Springboot | https://github.com/aws-observability/aws-otel-java-instrumentation/tree/main/sample-apps/springboot | Emit metrics to Xray | Java | X-ray sample app | 9/22/2021 | NathanielRN, anuraaga |   |  
opentelemetry-lambda | dotnet/sample-apps/aws-sdk/wrapper/SampleApps/AwsSdkSample | https://github.com/open-telemetry/opentelemetry-lambda/tree/main/dotnet/sample-apps/aws-sdk/wrapper/SampleApps/AwsSdkSample | .NET lambda layer for tracing | .NET | Upstream | 5/26/2021 | Anuraaga | https://github.com/open-telemetry/opentelemetry-lambda/commit/c58c998138f355b1faa5fa071a645ca37895ccb3 |  
go/sample-apps/function/ | https://github.com/open-telemetry/opentelemetry-lambda/tree/main/go/sample-apps/function | Go lambda layer for tracing | Go | Upstream | 11/15/2021 | Anuraaga | https://github.com/open-telemetry/opentelemetry-lambda/commit/85e2be9ac13c92807d27721179801b7f6461f884 |  
java/sample-apps/aws-sdk/ | https://github.com/open-telemetry/opentelemetry-lambda/tree/main/java/sample-apps/aws-sdk | Java lambda for otlp metric exporter using java sdk | Java | Upstream | 9/22/2021 | Anuraaga | https://github.com/open-telemetry/opentelemetry-lambda/commit/c0f2f1f80bf9062fb17f95e6ea4c1919fc6470fd |  
java/sample-apps/okhttp/ | https://github.com/open-telemetry/opentelemetry-lambda/tree/main/java/sample-apps/okhttp | Java lambda using OkHTTP client with tracing | Java | Upstream | 4/26/2021 | Anuraaga | https://github.com/open-telemetry/opentelemetry-lambda/commit/de4dc9f673f5249175eff589eac211459ddf13f0 |  
nodejs/sample-apps/aws-sdk/ | https://github.com/open-telemetry/opentelemetry-lambda/tree/main/nodejs/sample-apps/aws-sdk | Auto instrimentation for | JS | Upstream | 8/27/2021 | Anuraaga | https://github.com/open-telemetry/opentelemetry-lambda/commit/7291037479e0424de3bc31811d681876460b79ad |  
python/sample-apps/function | https://github.com/open-telemetry/opentelemetry-lambda/tree/main/python/sample-apps/function | Tracing a Python Lambda with Auto-Instrumentation OTel Python | Python | Upstream | 3/22/2021 | Anuraaga | https://github.com/open-telemetry/opentelemetry-lambda/blob/main/python/sample-apps/function/lambda_function.py
