### ISSUE TITLE
 cannot unmarshal string into Go struct field XRayMetaData.aws.xray.auto_instrumentation of type bool

### ISSUE THREAD

**Issue by thienlh96** [aws-observability/aws-otel-collector#830]
**Describe the bug**
2021-12-23T16:28:00.847Z warn awsxrayreceiver@v0.38.0/receiver.go:125 X-Ray segment to OT traces conversion failed {"kind": "receiver", "name": "awsxray", "error": "json: cannot unmarshal string into Go struct field XRayMetaData.aws.xray.auto_instrumentation of type bool"}

**Environment**
Application .Net use agent to auto instrusment
[.Net agent](https://github.com/aws/aws-xray-dotnet-agent)

**Comment by sethAmazon** [comment]
@willarmiros can you comment on if the auto instrumentation should send the agent a bool or a string for XRayMetaData.aws.xray.auto_instrumentation

**Comment by willarmiros** [comment]
Hi @thienlh96,

It seems like `auto_instrumentation` should in fact be allowed to be recorded as a bool:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/38668ef013261b04e3de7b9d3a5bf0a100d7cbff/internal/aws/xray/tracesegment.go#L262

I thought it was because the type is `*bool`, but that's how other booleans are recorded. Also the auto-instrumentation attribute isn't included in the unit test:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/38668ef013261b04e3de7b9d3a5bf0a100d7cbff/internal/aws/xray/tracesegment_test.go#L64-L65

One other thing I noticed is that `auto_instrumentation` doesn't have the `omitempty` attribute, which the other bools do. Regardless, we should investigate and fix the unit tests.

**Comment by sethAmazon** [comment]
@willarmiros I think what the error is saying is that the collector is receiving a string when expecting a bool. We can't tests this because the compiler will not let us.

**Comment by sethAmazon** [comment]
@thienlh96 anyway you can post what the collector receives from the app.

**Comment by lupengamzn** [comment]
Hello @thienlh96,

I believe this PR should fix the issue you met: https://github.com/aws/aws-xray-dotnet-agent/pull/42
