### ISSUE TITLE
Many examples still using old aws-otel-emitter image

### ISSUE THREAD

**Issue by jefchien** [aws-observability/aws-otel-collector#831]
As brought up by https://github.com/aws-observability/aws-otel-collector/pull/822, many of the examples still use the old sample app: `aottestbed/aws-otel-collector-sample-app:java-0.1.0`. This is no longer compatible with the collector and needs to be updated. The `examples/docker/docker-compose.yaml` was previously updated to `public.ecr.aws/aws-otel-test/aws-otel-java-test-spark:v0.11.0`. Need to evaluate if that image is still valid or if an updated sample app needs to be made available.

**Comment by vasireddy99** [comment]
public.ecr.aws/aws-otel-test/aws-otel-java-test-spark:v0.11.0 needs to be updated, since it doesn't have the changes form the PR#124 

This issue will be closed once the images are published with latest tag. will update all examples that are using the old aws-otel-emitter-image
eg : public.ecr.aws/aws-otel-test/aws-otel-java-test-spark:latest

cc : @jefchien @alolita
