### ISSUE TITLE
Send OTLP traces from Ruby to xray. 

### ISSUE THREAD

**Issue by alanlacombe-ring** [aws-observability/aws-otel-collector#905]
**Describe the question**
We are trying to send OTLP traces to XRay via ADOT and getting error because trace ids are not in xray format. Is there an xray-generator for ruby (like we see for go/python/java)? Alternatively is there a roadmap item from xray team to accept otlp formatted trace ids?

**Steps to reproduce if your question is related to an action**
From Ruby app send otlp traces to adot and have xray as exporter in pipeline.

**What did you expect to see?**
XRay accept the otlp formatted trace. We can send same data to tempo and zipkin and they accept it but xray does not.

**Environment**
Describe any aspect of your environment.

**Additional context**
We are still in evaluation between using xray and tempo.

**Comment by anuraaga** [comment]
Hi @alanlacombe-ring - Ruby support for ADOT has not been officially launched yet but is currently in progress. Docs should come soon, but in the meantime we do have a sample app somewhat ready. Can it provide the pointers you need?

https://github.com/aws-observability/aws-otel-ruby/blob/main/sample-apps/manual-instrumentation/ruby-on-rails/config/initializers/opentelemetry.rb#L4

**Comment by anuraaga** [comment]
@alanlacombe-ring Ah sorry I didn't realize that repo is still private as it's getting ready for launch. Stay tuned it should be ready soon.

**Comment by willarmiros** [comment]
Hi @alanlacombe-ring - thanks for your patience, ADOT Ruby is now available in public preview for tracing with X-Ray: https://aws-otel.github.io/docs/getting-started/ruby-sdk

Note that because it is public preview, we do not yet recommend it for production apps, however we welcome you to play around with it and post any bugs/feature gaps in https://github.com/aws-observability/aws-otel-ruby
