### ISSUE TITLE
No traces/metrics generated in CloudWatch Console when AWSOTelCollector deployed on Amazon EKS as sidecar

### ISSUE THREAD

**Issue by swetharavichandrancisco** [aws-observability/aws-otel-collector#933]
https://github.com/aws-observability/aws-otel-collector/blob/main/docs/developers/eks-demo.md - I followed the exact steps mentioned in the doc, but it did not generate traces/metrics to CloudWatch Console.

**### Steps that I followed:**
-  Created a EKS cluster
-  Created a policy "EKS-AWSOTel IAM Policy" as mentioned and attached to my worker [nodes.]
- Created IAM OIDC identity provider for my Amazon EKS cluster. 
- Created  service account named "api-service-account" with RBAC and linked my node instance role with its role-arn annotation
- Attached my yaml [sample.txt](https://github.com/aws-observability/aws-otel-collector/files/7961226/sample.txt) that I used for deploying in my cluster 

I have deployed my sample application and otel-collector as sidecar. 

### **Framework/Environment Used:**
- Sample appplication used is Asp.NET core.
- Run on EKS Linux

After generating the load, traces were generated in **AWS XRay**, but **not in Cloud Watch**. Is there anything missing in my setup?. Thanks in Advance.

**Comment by jefchien** [comment]
Hi @swetharavichandrancisco,

I believe the issue was caused when we switched our sample apps. We need to add the environment variable `OTLP_METRIC_EXPORTER` and set it to `otlp` for the configuration to work. (source: https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure#otlp-exporter-span-metric-and-log-exporters). I'll make the changes to our examples.

Thanks for finding the issue!
