### ISSUE TITLE
Reduce CD workflow steps

### ISSUE THREAD

**Issue by bryan-aguilar** [aws-observability/aws-otel-collector#948]
**Is your feature request related to a problem? Please describe.**
The current C/D workflow runs a subset of integration tests against the released image to confirm that no corruption occurred on upload. This task is very time consuming and redundant since test have already been run during the CI phase. 

**Describe the solution you'd like**
Instead of running tests during C/D, trust that C/I has performed all proper tests and instead compare checksums / digests to ensure image validity.

**Comment by bryan-aguilar** [comment]
@mxiamxia Would you be able to provide any context if these tests are necessary for future releases?

**Comment by khanhntd** [comment]
One of my intentions is to [combine the integration test such as hitting all the validation endpoints instead of hitting separately ](https://github.com/aws-observability/aws-otel-collector/issues/834). One point that I need to point out is that the build in CI tests sometimes are not up-to-date (meaning each CI tests can have different builds, therefore, CD also acts as integration tests too).

**Comment by bryan-aguilar** [comment]
I think I understand your last point but that may be a separate issue entirely. I feel like I need to ask a naive question. Other than your last point why does the CD workflow require more validation other than verifying image validity through hashes? Saying that our "CD needs to fulfill roles of the CI also" does not seem like a best practice.
