### ISSUE TITLE
Update references to ADOT Collector

### ISSUE THREAD

**Issue by bryan-aguilar** [aws-observability/aws-otel-collector#971]
**Is your feature request related to a problem? Please describe.**
Documentation throughout the repository refers to the `ADOT Collector` as `AWS Collector`. This is incorrect and needs to be fixed. Long form nomenclature is `AWS Distro for OpenTelemetry` and the short form is `ADOT Collector`. 

**Describe the solution you'd like**
Fix Docs

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by vasireddy99** [comment]
I Think if its `AWS OTel collector` should be fine for now?, since there are naming conventions for the repo itself such as `aws-otel-test-framework`, may be its good that we can track this issue to make changes for the documentation. But yes, I agree if its `AWS Collector` should be renamed in the documentation :-)

**Comment by alolita** [comment]
AWS OTEL Collector is not the right usage. The long form and abbreviation are as Bryan noted and should be updated in all docs for consistent and correct usage.
